### ISSUE TITLE
BUG: 重启服务后设置的LOGIN_API_TOKEN失效

### ISSUE THREAD

**Issue by shaojun-tes** [danni-cool/wechatbot-webhook#102]
今天更新到最新版本dannicool/docker-wechatbot-webhook:nightly，重启服务后设置的LOGIN_API_TOKEN失效，可以直接通过http://localhost:3001/login访问，不需要带?token=XXX参数。

**Comment by danni-cool** [comment]
@shaojun-tes 感谢反馈，但是并没有复现，nightly 代码和 latest 是同步的

**Comment by shaojun-tes** [comment]
复现步骤：
1. 拉取arm64镜像： 
```
docker pull --platform arm64 dannicool/docker-wechatbot-webhook:nightly
```
2. 进入镜像
```
docker run --rm  -it --privileged --entrypoint sh dannicool/docker-wechatbot-webhook:nightly
```
3. 打包/app目录
```
cd /
tar czvf app.tgz app
```
4. 将打包好的app.tgz传至手机的termux,并解压运行
解压app.tgz后，将如下脚本startapp.sh放入./app目录中，并执行bash startapp.sh运行
cat startapp.sh
```bash
workdir=`cd $(dirname $0);pwd`
export RECVD_MSG_API='http://127.0.0.1:8080/api/v1/wxmsg'
export LOGIN_API_TOKEN='1qaz2wsxa'

cd $workdir
nohup npm start > nohup.out 2>&1 &
```
5. 获得登陆连接，然后扫码登陆
```
curl 'http://localhost:3001/login?token=1qaz2wsxa' 
```
6. 访问/login接口，正常返回
```
curl 'http://localhost:3001/login?token=1qaz2wsxa' 
```
返回
```
"success":true,"message":"Contact<xxxxx>is already login"}
```

以上都是正常的步骤，

**重点步骤来了**
7. kill npm
```
pkill npm
```
8. 再次执行启动脚本bash startapp.sh
因为loginSession.memory-card.json文件存在，所以不需要登陆
```
bash startapp.sh
```
这个时候带token去访问/login接口
```
curl 'http://localhost:3001/login?token=1qaz2wsxa' 
```
提示就不正常了，如下

```
{"success":false,"message":"Unauthorized: Access is denied due to invalid credentials."}
```
尝试不带token访问
curl 'http://localhost:3001/login
```
"success":true,"message":"Contact<xxxxx>is already login"}

```

**Comment by shaojun-tes** [comment]
截图如下： 
![image](https://github.com/danni-cool/wechatbot-webhook/assets/83997493/cb419d7d-c0db-4098-a767-e13951a5cb7a)

**Comment by shaojun-tes** [comment]
尝试用旧版本，没有commitlint.config.js这个自动登陆功能，就没有以上问题

**Comment by danni-cool** [comment]
@shaojun-tes 复现步骤很清晰，点个赞，已经找到问题所在

**Comment by danni-cool** [comment]
既然你拉镜像是为了打包源代码，为何不直接用github发布的包 https://github.com/danni-cool/wechatbot-webhook/releases/tag/v2.4.2

**Comment by shaojun-tes** [comment]
因为我使用中发现，我只能接收消息，不能发消息，一尝试发消息，CPU就打满，一段时间内程序假死，甚至可能和微信服务器间都没有心跳，导致被下线。然后只能杀了重启。 但我在电脑上使用没这问题，所以我想是不是针对arm64有什么优化， 所以想拉取dannicool/docker-wechatbot-webhook:nightly针对arm64的镜像试试

**Comment by danni-cool** [comment]
观察下文本类和文件类的消息差异，前者我理解应该是纯http请求，后者可能涉及到文件下载，也许会多占用一些内存

**Comment by shaojun-tes** [comment]
还没有涉及发文件的情况，就是一个简单的hello world.
猜测是底层利用单核查找这个要发送的用户，造成CPU利用率高。

```
curl --location --request POST 'http://localhost:3001/webhook/msg?tokne=1qaz2wsx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "to": "MyTestWX",
    "type": "text",
    "content": "Hello World!"
}'
```

不管怎么样，非常感谢大佬这么快速的修复了[LOGIN_API_TOKEN失效]的问题！ 谢谢！

**Comment by danni-cool** [comment]
后期会补上单测，下个版本应该会增加单api收消息的功能及用更轻量的http服务，不知道有无改善

**Comment by Daydaylw3** [comment]
大佬 @danni-cool 我这边就只是使用 docker-compose.yml 启动镜像，然后请求 /healthz 时也是返回了`Unauthorized: Access is denied due to invalid credentials.`

docker-compose.yml 文件如下：

```yml
version: '3'

services:
  wxBotWebhook:
    image: dannicool/docker-wechatbot-webhook
    container_name: wxBotWebhook
    ports:
      - "3001:3001"
    volumes:
      - ~/Documents/docker/log/wechatbot:/app/log
    environment:
      - LOGIN_API_TOKEN=dayday
      - RECVD_MSG_API=http://192.168.2.90:7777/receive/msg
    restart: always
```
