### ISSUE TITLE
Docker 部署后请求不到登录二维码

### ISSUE THREAD

**Issue by 1657744680** [danni-cool/wechatbot-webhook#134]
在群晖 NAS 上部署：
```
version: '3.8'
services:
  wxBotWebhook:
    image: dannicool/docker-wechatbot-webhook
    container_name: wxBotWebhook
    volumes:
      - /volume1/docker/wxBotWebhook/logs:/app/log
    ports:
      - "3001:3001"
    environment:
      - LOG_LEVEL=info # 调整容器输出级别（不影响日志文件输出等级）运行时提示的消息等级（默认info，想有更详细的日志，等级同log4js)
      # - DISABLE_AUTO_LOGIN=true # 如果不希望登录一次后就记住当前账号，想每次都扫码登陆，填 true
      # - LOCAL_RECVD_MSG_API= # 如果想自己处理收到消息的逻辑，在下面填上你的API地址, 默认为空
      - LOGIN_API_TOKEN=wd
      - LOCAL_LOGIN_API_TOKEN=wd # 登录地址Token访问地址： http://localhost:3001/login?token=[LOCAL_LOGIN_API_TOKEN]
    restart: unless-stopped
```

访问 http://localhost:3001/login?token=wd 后无法获取登录二维码😭

日志：
```
[ERROR] - 
AxiosError: timeout of 60000ms exceeded
```
